// أنواع البيانات المحدثة لقاعدة البيانات الشاملة
export interface Database {
  public: {
    Tables: {
      // الجداول الموجودة مسبقاً
      roles: {
        Row: {
          id: string;
          name: string;
          description: string;
          permissions: string[];
          user_count: number;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          permissions: string[];
          user_count?: number;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          permissions?: string[];
          user_count?: number;
          is_active?: boolean;
          created_at?: string;
        };
      };
      system_users: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          role_id: string;
          status: 'active' | 'inactive' | 'suspended';
          last_login: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          role_id: string;
          status?: 'active' | 'inactive' | 'suspended';
          last_login?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          role_id?: string;
          status?: 'active' | 'inactive' | 'suspended';
          last_login?: string;
          created_at?: string;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          type: string;
          location: string;
          contact_person: string;
          phone: string;
          email: string;
          beneficiaries_count: number;
          packages_count: number;
          completion_rate: number;
          status: 'active' | 'pending' | 'suspended';
          created_at: string;
          packages_available: number;
          templates_count: number;
          is_popular: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          type: string;
          location: string;
          contact_person: string;
          phone: string;
          email: string;
          beneficiaries_count?: number;
          packages_count?: number;
          completion_rate?: number;
          status?: 'active' | 'pending' | 'suspended';
          created_at?: string;
          packages_available?: number;
          templates_count?: number;
          is_popular?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          location?: string;
          contact_person?: string;
          phone?: string;
          email?: string;
          beneficiaries_count?: number;
          packages_count?: number;
          completion_rate?: number;
          status?: 'active' | 'pending' | 'suspended';
          created_at?: string;
          packages_available?: number;
          templates_count?: number;
          is_popular?: boolean;
        };
      };
      families: {
        Row: {
          id: string;
          name: string;
          head_of_family: string;
          phone: string;
          members_count: number;
          packages_distributed: number;
          completion_rate: number;
          location: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          head_of_family: string;
          phone: string;
          members_count?: number;
          packages_distributed?: number;
          completion_rate?: number;
          location: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          head_of_family?: string;
          phone?: string;
          members_count?: number;
          packages_distributed?: number;
          completion_rate?: number;
          location?: string;
          created_at?: string;
        };
      };
      beneficiaries: {
        Row: {
          id: string;
          name: string;
          full_name: string;
          national_id: string;
          date_of_birth: string;
          gender: 'male' | 'female';
          phone: string;
          address: string;
          detailed_address: any;
          location: any;
          organization_id?: string;
          family_id?: string;
          relation_to_family?: string;
          profession: string;
          marital_status: 'single' | 'married' | 'divorced' | 'widowed';
          economic_level: 'very_poor' | 'poor' | 'moderate' | 'good';
          members_count: number;
          additional_documents: any;
          identity_status: 'verified' | 'pending' | 'rejected';
          identity_image_url?: string;
          status: 'active' | 'pending' | 'suspended';
          eligibility_status: 'eligible' | 'under_review' | 'rejected';
          last_received: string;
          total_packages: number;
          notes: string;
          created_at: string;
          updated_at: string;
          created_by: string;
          updated_by: string;
        };
        Insert: {
          id?: string;
          name: string;
          full_name: string;
          national_id: string;
          date_of_birth: string;
          gender: 'male' | 'female';
          phone: string;
          address: string;
          detailed_address: any;
          location: any;
          organization_id?: string;
          family_id?: string;
          relation_to_family?: string;
          profession: string;
          marital_status: 'single' | 'married' | 'divorced' | 'widowed';
          economic_level: 'very_poor' | 'poor' | 'moderate' | 'good';
          members_count?: number;
          additional_documents?: any;
          identity_status?: 'verified' | 'pending' | 'rejected';
          identity_image_url?: string;
          status?: 'active' | 'pending' | 'suspended';
          eligibility_status?: 'eligible' | 'under_review' | 'rejected';
          last_received?: string;
          total_packages?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          name?: string;
          full_name?: string;
          national_id?: string;
          date_of_birth?: string;
          gender?: 'male' | 'female';
          phone?: string;
          address?: string;
          detailed_address?: any;
          location?: any;
          organization_id?: string;
          family_id?: string;
          relation_to_family?: string;
          profession?: string;
          marital_status?: 'single' | 'married' | 'divorced' | 'widowed';
          economic_level?: 'very_poor' | 'poor' | 'moderate' | 'good';
          members_count?: number;
          additional_documents?: any;
          identity_status?: 'verified' | 'pending' | 'rejected';
          identity_image_url?: string;
          status?: 'active' | 'pending' | 'suspended';
          eligibility_status?: 'eligible' | 'under_review' | 'rejected';
          last_received?: string;
          total_packages?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
      };
      packages: {
        Row: {
          id: string;
          name: string;
          type: string;
          description: string;
          value: number;
          funder: string;
          organization_id?: string;
          family_id?: string;
          beneficiary_id?: string;
          status: 'pending' | 'assigned' | 'in_delivery' | 'delivered' | 'failed';
          created_at: string;
          delivered_at?: string;
          expiry_date?: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: string;
          description: string;
          value: number;
          funder: string;
          organization_id?: string;
          family_id?: string;
          beneficiary_id?: string;
          status?: 'pending' | 'assigned' | 'in_delivery' | 'delivered' | 'failed';
          created_at?: string;
          delivered_at?: string;
          expiry_date?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: string;
          description?: string;
          value?: number;
          funder?: string;
          organization_id?: string;
          family_id?: string;
          beneficiary_id?: string;
          status?: 'pending' | 'assigned' | 'in_delivery' | 'delivered' | 'failed';
          created_at?: string;
          delivered_at?: string;
          expiry_date?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          package_id: string;
          beneficiary_id: string;
          courier_id?: string;
          status: 'pending' | 'assigned' | 'in_progress' | 'delivered' | 'failed' | 'rescheduled';
          created_at: string;
          scheduled_at?: string;
          delivered_at?: string;
          delivery_location?: any;
          notes?: string;
          courier_notes?: string;
          delivery_proof_image_url?: string;
          digital_signature_image_url?: string;
          estimated_arrival_time?: string;
          remaining_distance?: number;
          photo_url?: string;
          failure_reason?: string;
        };
        Insert: {
          id?: string;
          package_id: string;
          beneficiary_id: string;
          courier_id?: string;
          status?: 'pending' | 'assigned' | 'in_progress' | 'delivered' | 'failed' | 'rescheduled';
          created_at?: string;
          scheduled_at?: string;
          delivered_at?: string;
          delivery_location?: any;
          notes?: string;
          courier_notes?: string;
          delivery_proof_image_url?: string;
          digital_signature_image_url?: string;
          estimated_arrival_time?: string;
          remaining_distance?: number;
          photo_url?: string;
          failure_reason?: string;
        };
        Update: {
          id?: string;
          package_id?: string;
          beneficiary_id?: string;
          courier_id?: string;
          status?: 'pending' | 'assigned' | 'in_progress' | 'delivered' | 'failed' | 'rescheduled';
          created_at?: string;
          scheduled_at?: string;
          delivered_at?: string;
          delivery_location?: any;
          notes?: string;
          courier_notes?: string;
          delivery_proof_image_url?: string;
          digital_signature_image_url?: string;
          estimated_arrival_time?: string;
          remaining_distance?: number;
          photo_url?: string;
          failure_reason?: string;
        };
      };
      alerts: {
        Row: {
          id: string;
          type: 'delayed' | 'failed' | 'expired' | 'urgent';
          title: string;
          description: string;
          related_id: string;
          related_type: 'package' | 'beneficiary' | 'task';
          priority: 'low' | 'medium' | 'high' | 'critical';
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: 'delayed' | 'failed' | 'expired' | 'urgent';
          title: string;
          description: string;
          related_id: string;
          related_type: 'package' | 'beneficiary' | 'task';
          priority?: 'low' | 'medium' | 'high' | 'critical';
          is_read?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: 'delayed' | 'failed' | 'expired' | 'urgent';
          title?: string;
          description?: string;
          related_id?: string;
          related_type?: 'package' | 'beneficiary' | 'task';
          priority?: 'low' | 'medium' | 'high' | 'critical';
          is_read?: boolean;
          created_at?: string;
        };
      };
      activity_log: {
        Row: {
          id: string;
          action: string;
          user_name: string;
          role: string;
          timestamp: string;
          type: 'create' | 'verify' | 'approve' | 'update' | 'deliver' | 'review';
          beneficiary_id?: string;
          details?: string;
        };
        Insert: {
          id?: string;
          action: string;
          user_name: string;
          role: string;
          timestamp?: string;
          type: 'create' | 'verify' | 'approve' | 'update' | 'deliver' | 'review';
          beneficiary_id?: string;
          details?: string;
        };
        Update: {
          id?: string;
          action?: string;
          user_name?: string;
          role?: string;
          timestamp?: string;
          type?: 'create' | 'verify' | 'approve' | 'update' | 'deliver' | 'review';
          beneficiary_id?: string;
          details?: string;
        };
      };
      couriers: {
        Row: {
          id: string;
          name: string;
          phone: string;
          email: string;
          status: 'active' | 'busy' | 'offline';
          rating: number;
          completed_tasks: number;
          current_location?: any;
          is_humanitarian_approved: boolean;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          email: string;
          status?: 'active' | 'busy' | 'offline';
          rating?: number;
          completed_tasks?: number;
          current_location?: any;
          is_humanitarian_approved?: boolean;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string;
          email?: string;
          status?: 'active' | 'busy' | 'offline';
          rating?: number;
          completed_tasks?: number;
          current_location?: any;
          is_humanitarian_approved?: boolean;
        };
      };
      package_templates: {
        Row: {
          id: string;
          name: string;
          type: 'food' | 'medical' | 'clothing' | 'hygiene' | 'emergency';
          organization_id: string;
          description: string;
          contents: any;
          status: 'active' | 'draft' | 'inactive';
          created_at: string;
          usage_count: number;
          total_weight: number;
          estimated_cost: number;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'food' | 'medical' | 'clothing' | 'hygiene' | 'emergency';
          organization_id: string;
          description: string;
          contents: any;
          status?: 'active' | 'draft' | 'inactive';
          created_at?: string;
          usage_count?: number;
          total_weight?: number;
          estimated_cost?: number;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'food' | 'medical' | 'clothing' | 'hygiene' | 'emergency';
          organization_id?: string;
          description?: string;
          contents?: any;
          status?: 'active' | 'draft' | 'inactive';
          created_at?: string;
          usage_count?: number;
          total_weight?: number;
          estimated_cost?: number;
        };
      };
      permissions: {
        Row: {
          id: string;
          name: string;
          description: string;
          category: 'read' | 'write' | 'delete' | 'approve' | 'manage';
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description: string;
          category: 'read' | 'write' | 'delete' | 'approve' | 'manage';
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          category?: 'read' | 'write' | 'delete' | 'approve' | 'manage';
          created_at?: string;
        };
      };
      // الجداول الجديدة
      institutions: {
        Row: {
          id: string;
          name: string;
          type: 'international' | 'local' | 'government' | 'ngo' | 'charity';
          category: 'food' | 'medical' | 'clothing' | 'shelter' | 'education' | 'mixed';
          country: string;
          region: string;
          city: string;
          address: string;
          contact_person: string;
          phone: string;
          email: string;
          website?: string;
          license_number?: string;
          registration_date?: string;
          status: 'active' | 'pending' | 'suspended' | 'inactive';
          funding_capacity: number;
          monthly_budget: number;
          beneficiaries_served: number;
          packages_distributed: number;
          success_rate: number;
          rating: number;
          is_verified: boolean;
          is_emergency_approved: boolean;
          logo_url?: string;
          description?: string;
          specializations: string[];
          working_hours: any;
          coverage_areas: string[];
          created_at: string;
          updated_at: string;
          created_by?: string;
          updated_by?: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'international' | 'local' | 'government' | 'ngo' | 'charity';
          category: 'food' | 'medical' | 'clothing' | 'shelter' | 'education' | 'mixed';
          country?: string;
          region: string;
          city: string;
          address: string;
          contact_person: string;
          phone: string;
          email: string;
          website?: string;
          license_number?: string;
          registration_date?: string;
          status?: 'active' | 'pending' | 'suspended' | 'inactive';
          funding_capacity?: number;
          monthly_budget?: number;
          beneficiaries_served?: number;
          packages_distributed?: number;
          success_rate?: number;
          rating?: number;
          is_verified?: boolean;
          is_emergency_approved?: boolean;
          logo_url?: string;
          description?: string;
          specializations?: string[];
          working_hours?: any;
          coverage_areas?: string[];
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'international' | 'local' | 'government' | 'ngo' | 'charity';
          category?: 'food' | 'medical' | 'clothing' | 'shelter' | 'education' | 'mixed';
          country?: string;
          region?: string;
          city?: string;
          address?: string;
          contact_person?: string;
          phone?: string;
          email?: string;
          website?: string;
          license_number?: string;
          registration_date?: string;
          status?: 'active' | 'pending' | 'suspended' | 'inactive';
          funding_capacity?: number;
          monthly_budget?: number;
          beneficiaries_served?: number;
          packages_distributed?: number;
          success_rate?: number;
          rating?: number;
          is_verified?: boolean;
          is_emergency_approved?: boolean;
          logo_url?: string;
          description?: string;
          specializations?: string[];
          working_hours?: any;
          coverage_areas?: string[];
          created_at?: string;
          updated_at?: string;
          created_by?: string;
          updated_by?: string;
        };
      };
      package_items: {
        Row: {
          id: string;
          template_id: string;
          name: string;
          category: 'food' | 'medicine' | 'clothing' | 'hygiene' | 'tools' | 'other';
          quantity: number;
          unit: string;
          weight_per_unit: number;
          cost_per_unit: number;
          expiry_date?: string;
          brand?: string;
          description?: string;
          nutritional_info?: any;
          storage_requirements?: string;
          handling_instructions?: string;
          is_essential: boolean;
          alternatives: string[];
          supplier?: string;
          barcode?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          template_id: string;
          name: string;
          category: 'food' | 'medicine' | 'clothing' | 'hygiene' | 'tools' | 'other';
          quantity: number;
          unit: string;
          weight_per_unit?: number;
          cost_per_unit?: number;
          expiry_date?: string;
          brand?: string;
          description?: string;
          nutritional_info?: any;
          storage_requirements?: string;
          handling_instructions?: string;
          is_essential?: boolean;
          alternatives?: string[];
          supplier?: string;
          barcode?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          template_id?: string;
          name?: string;
          category?: 'food' | 'medicine' | 'clothing' | 'hygiene' | 'tools' | 'other';
          quantity?: number;
          unit?: string;
          weight_per_unit?: number;
          cost_per_unit?: number;
          expiry_date?: string;
          brand?: string;
          description?: string;
          nutritional_info?: any;
          storage_requirements?: string;
          handling_instructions?: string;
          is_essential?: boolean;
          alternatives?: string[];
          supplier?: string;
          barcode?: string;
          created_at?: string;
        };
      };
      delivery_routes: {
        Row: {
          id: string;
          name: string;
          start_location: any;
          end_location: any;
          waypoints: any;
          distance_km?: number;
          estimated_duration_minutes?: number;
          difficulty_level: 'easy' | 'normal' | 'hard' | 'dangerous';
          safety_rating: number;
          road_conditions?: string;
          checkpoints: any;
          restrictions: string[];
          best_time_slots: string[];
          weather_dependent: boolean;
          vehicle_requirements: string[];
          is_active: boolean;
          usage_count: number;
          success_rate: number;
          average_completion_time?: number;
          last_used?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          start_location: any;
          end_location: any;
          waypoints?: any;
          distance_km?: number;
          estimated_duration_minutes?: number;
          difficulty_level?: 'easy' | 'normal' | 'hard' | 'dangerous';
          safety_rating?: number;
          road_conditions?: string;
          checkpoints?: any;
          restrictions?: string[];
          best_time_slots?: string[];
          weather_dependent?: boolean;
          vehicle_requirements?: string[];
          is_active?: boolean;
          usage_count?: number;
          success_rate?: number;
          average_completion_time?: number;
          last_used?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          start_location?: any;
          end_location?: any;
          waypoints?: any;
          distance_km?: number;
          estimated_duration_minutes?: number;
          difficulty_level?: 'easy' | 'normal' | 'hard' | 'dangerous';
          safety_rating?: number;
          road_conditions?: string;
          checkpoints?: any;
          restrictions?: string[];
          best_time_slots?: string[];
          weather_dependent?: boolean;
          vehicle_requirements?: string[];
          is_active?: boolean;
          usage_count?: number;
          success_rate?: number;
          average_completion_time?: number;
          last_used?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      courier_locations: {
        Row: {
          id: string;
          courier_id: string;
          latitude: number;
          longitude: number;
          accuracy?: number;
          altitude?: number;
          speed?: number;
          heading?: number;
          timestamp: string;
          location_type: 'gps' | 'manual' | 'estimated';
          battery_level?: number;
          signal_strength?: number;
          is_active: boolean;
          address_description?: string;
          landmark?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          courier_id: string;
          latitude: number;
          longitude: number;
          accuracy?: number;
          altitude?: number;
          speed?: number;
          heading?: number;
          timestamp?: string;
          location_type?: 'gps' | 'manual' | 'estimated';
          battery_level?: number;
          signal_strength?: number;
          is_active?: boolean;
          address_description?: string;
          landmark?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          courier_id?: string;
          latitude?: number;
          longitude?: number;
          accuracy?: number;
          altitude?: number;
          speed?: number;
          heading?: number;
          timestamp?: string;
          location_type?: 'gps' | 'manual' | 'estimated';
          battery_level?: number;
          signal_strength?: number;
          is_active?: boolean;
          address_description?: string;
          landmark?: string;
          created_at?: string;
        };
      };
      beneficiary_categories: {
        Row: {
          id: string;
          name: string;
          description?: string;
          priority_level: number;
          eligibility_criteria: any;
          required_documents: string[];
          benefits_entitled: string[];
          review_frequency_days: number;
          auto_approval: boolean;
          color_code: string;
          icon: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          priority_level?: number;
          eligibility_criteria?: any;
          required_documents?: string[];
          benefits_entitled?: string[];
          review_frequency_days?: number;
          auto_approval?: boolean;
          color_code?: string;
          icon?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          priority_level?: number;
          eligibility_criteria?: any;
          required_documents?: string[];
          benefits_entitled?: string[];
          review_frequency_days?: number;
          auto_approval?: boolean;
          color_code?: string;
          icon?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      distribution_centers: {
        Row: {
          id: string;
          name: string;
          type: 'main' | 'secondary' | 'mobile' | 'emergency';
          location: any;
          address: string;
          capacity: number;
          current_stock: number;
          manager_name: string;
          manager_phone: string;
          operating_hours: any;
          facilities: string[];
          storage_conditions: string[];
          security_level: 'basic' | 'standard' | 'high' | 'maximum';
          accessibility_features: string[];
          coverage_radius_km: number;
          status: 'active' | 'maintenance' | 'closed' | 'emergency_only';
          last_inspection_date?: string;
          certification_status: 'pending' | 'certified' | 'expired' | 'suspended';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type?: 'main' | 'secondary' | 'mobile' | 'emergency';
          location: any;
          address: string;
          capacity?: number;
          current_stock?: number;
          manager_name: string;
          manager_phone: string;
          operating_hours?: any;
          facilities?: string[];
          storage_conditions?: string[];
          security_level?: 'basic' | 'standard' | 'high' | 'maximum';
          accessibility_features?: string[];
          coverage_radius_km?: number;
          status?: 'active' | 'maintenance' | 'closed' | 'emergency_only';
          last_inspection_date?: string;
          certification_status?: 'pending' | 'certified' | 'expired' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'main' | 'secondary' | 'mobile' | 'emergency';
          location?: any;
          address?: string;
          capacity?: number;
          current_stock?: number;
          manager_name?: string;
          manager_phone?: string;
          operating_hours?: any;
          facilities?: string[];
          storage_conditions?: string[];
          security_level?: 'basic' | 'standard' | 'high' | 'maximum';
          accessibility_features?: string[];
          coverage_radius_km?: number;
          status?: 'active' | 'maintenance' | 'closed' | 'emergency_only';
          last_inspection_date?: string;
          certification_status?: 'pending' | 'certified' | 'expired' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
      };
      inventory: {
        Row: {
          id: string;
          distribution_center_id: string;
          item_name: string;
          item_category: string;
          current_quantity: number;
          reserved_quantity: number;
          minimum_threshold: number;
          maximum_capacity: number;
          unit: string;
          cost_per_unit: number;
          supplier?: string;
          batch_number?: string;
          expiry_date?: string;
          storage_location?: string;
          condition_status: 'excellent' | 'good' | 'fair' | 'poor' | 'expired';
          last_counted_date?: string;
          last_restocked_date?: string;
          reorder_point: number;
          is_critical: boolean;
          notes?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          distribution_center_id: string;
          item_name: string;
          item_category: string;
          current_quantity?: number;
          reserved_quantity?: number;
          minimum_threshold?: number;
          maximum_capacity?: number;
          unit: string;
          cost_per_unit?: number;
          supplier?: string;
          batch_number?: string;
          expiry_date?: string;
          storage_location?: string;
          condition_status?: 'excellent' | 'good' | 'fair' | 'poor' | 'expired';
          last_counted_date?: string;
          last_restocked_date?: string;
          reorder_point?: number;
          is_critical?: boolean;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          distribution_center_id?: string;
          item_name?: string;
          item_category?: string;
          current_quantity?: number;
          reserved_quantity?: number;
          minimum_threshold?: number;
          maximum_capacity?: number;
          unit?: string;
          cost_per_unit?: number;
          supplier?: string;
          batch_number?: string;
          expiry_date?: string;
          storage_location?: string;
          condition_status?: 'excellent' | 'good' | 'fair' | 'poor' | 'expired';
          last_counted_date?: string;
          last_restocked_date?: string;
          reorder_point?: number;
          is_critical?: boolean;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          recipient_type: 'user' | 'beneficiary' | 'courier' | 'organization' | 'all';
          recipient_id?: string;
          title: string;
          message: string;
          type: 'info' | 'warning' | 'error' | 'success' | 'urgent';
          priority: 'low' | 'normal' | 'high' | 'critical';
          channel: 'app' | 'sms' | 'email' | 'push' | 'whatsapp';
          status: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
          scheduled_at?: string;
          sent_at?: string;
          read_at?: string;
          metadata: any;
          template_id?: string;
          related_entity_type?: string;
          related_entity_id?: string;
          retry_count: number;
          max_retries: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          recipient_type: 'user' | 'beneficiary' | 'courier' | 'organization' | 'all';
          recipient_id?: string;
          title: string;
          message: string;
          type: 'info' | 'warning' | 'error' | 'success' | 'urgent';
          priority?: 'low' | 'normal' | 'high' | 'critical';
          channel?: 'app' | 'sms' | 'email' | 'push' | 'whatsapp';
          status?: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
          scheduled_at?: string;
          sent_at?: string;
          read_at?: string;
          metadata?: any;
          template_id?: string;
          related_entity_type?: string;
          related_entity_id?: string;
          retry_count?: number;
          max_retries?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          recipient_type?: 'user' | 'beneficiary' | 'courier' | 'organization' | 'all';
          recipient_id?: string;
          title?: string;
          message?: string;
          type?: 'info' | 'warning' | 'error' | 'success' | 'urgent';
          priority?: 'low' | 'normal' | 'high' | 'critical';
          channel?: 'app' | 'sms' | 'email' | 'push' | 'whatsapp';
          status?: 'pending' | 'sent' | 'delivered' | 'read' | 'failed';
          scheduled_at?: string;
          sent_at?: string;
          read_at?: string;
          metadata?: any;
          template_id?: string;
          related_entity_type?: string;
          related_entity_id?: string;
          retry_count?: number;
          max_retries?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      geographic_areas: {
        Row: {
          id: string;
          name: string;
          type: 'governorate' | 'city' | 'district' | 'neighborhood' | 'camp';
          parent_id?: string;
          boundaries?: any;
          center_point?: any;
          population?: number;
          area_km2?: number;
          postal_code?: string;
          security_level: 'safe' | 'normal' | 'caution' | 'dangerous' | 'restricted';
          accessibility: 'accessible' | 'limited' | 'difficult' | 'inaccessible';
          infrastructure_quality: 'excellent' | 'good' | 'fair' | 'poor';
          delivery_difficulty: 'easy' | 'normal' | 'hard' | 'very_hard';
          average_delivery_time_minutes: number;
          preferred_delivery_times: string[];
          special_instructions?: string;
          landmarks: string[];
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: 'governorate' | 'city' | 'district' | 'neighborhood' | 'camp';
          parent_id?: string;
          boundaries?: any;
          center_point?: any;
          population?: number;
          area_km2?: number;
          postal_code?: string;
          security_level?: 'safe' | 'normal' | 'caution' | 'dangerous' | 'restricted';
          accessibility?: 'accessible' | 'limited' | 'difficult' | 'inaccessible';
          infrastructure_quality?: 'excellent' | 'good' | 'fair' | 'poor';
          delivery_difficulty?: 'easy' | 'normal' | 'hard' | 'very_hard';
          average_delivery_time_minutes?: number;
          preferred_delivery_times?: string[];
          special_instructions?: string;
          landmarks?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: 'governorate' | 'city' | 'district' | 'neighborhood' | 'camp';
          parent_id?: string;
          boundaries?: any;
          center_point?: any;
          population?: number;
          area_km2?: number;
          postal_code?: string;
          security_level?: 'safe' | 'normal' | 'caution' | 'dangerous' | 'restricted';
          accessibility?: 'accessible' | 'limited' | 'difficult' | 'inaccessible';
          infrastructure_quality?: 'excellent' | 'good' | 'fair' | 'poor';
          delivery_difficulty?: 'easy' | 'normal' | 'hard' | 'very_hard';
          average_delivery_time_minutes?: number;
          preferred_delivery_times?: string[];
          special_instructions?: string;
          landmarks?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      emergency_contacts: {
        Row: {
          id: string;
          beneficiary_id: string;
          name: string;
          relationship: string;
          phone: string;
          alternative_phone?: string;
          address?: string;
          is_primary: boolean;
          can_receive_packages: boolean;
          notes?: string;
          verified: boolean;
          verified_date?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          beneficiary_id: string;
          name: string;
          relationship: string;
          phone: string;
          alternative_phone?: string;
          address?: string;
          is_primary?: boolean;
          can_receive_packages?: boolean;
          notes?: string;
          verified?: boolean;
          verified_date?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          beneficiary_id?: string;
          name?: string;
          relationship?: string;
          phone?: string;
          alternative_phone?: string;
          address?: string;
          is_primary?: boolean;
          can_receive_packages?: boolean;
          notes?: string;
          verified?: boolean;
          verified_date?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      feedback: {
        Row: {
          id: string;
          beneficiary_id: string;
          task_id: string;
          courier_id?: string;
          package_id?: string;
          rating?: number;
          service_quality_rating?: number;
          delivery_time_rating?: number;
          package_condition_rating?: number;
          courier_behavior_rating?: number;
          comments?: string;
          suggestions?: string;
          complaints?: string;
          would_recommend?: boolean;
          feedback_type: 'delivery' | 'service' | 'complaint' | 'suggestion';
          status: 'pending' | 'reviewed' | 'resolved' | 'escalated';
          response?: string;
          responded_by?: string;
          responded_at?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          beneficiary_id: string;
          task_id: string;
          courier_id?: string;
          package_id?: string;
          rating?: number;
          service_quality_rating?: number;
          delivery_time_rating?: number;
          package_condition_rating?: number;
          courier_behavior_rating?: number;
          comments?: string;
          suggestions?: string;
          complaints?: string;
          would_recommend?: boolean;
          feedback_type?: 'delivery' | 'service' | 'complaint' | 'suggestion';
          status?: 'pending' | 'reviewed' | 'resolved' | 'escalated';
          response?: string;
          responded_by?: string;
          responded_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          beneficiary_id?: string;
          task_id?: string;
          courier_id?: string;
          package_id?: string;
          rating?: number;
          service_quality_rating?: number;
          delivery_time_rating?: number;
          package_condition_rating?: number;
          courier_behavior_rating?: number;
          comments?: string;
          suggestions?: string;
          complaints?: string;
          would_recommend?: boolean;
          feedback_type?: 'delivery' | 'service' | 'complaint' | 'suggestion';
          status?: 'pending' | 'reviewed' | 'resolved' | 'escalated';
          response?: string;
          responded_by?: string;
          responded_at?: string;
          created_at?: string;
        };
      };
      // إضافة باقي الجداول الجديدة...
      user_sessions: {
        Row: {
          id: string;
          user_id: string;
          session_token: string;
          ip_address?: string;
          user_agent?: string;
          device_info: any;
          location_info: any;
          login_time: string;
          last_activity: string;
          logout_time?: string;
          status: 'active' | 'expired' | 'terminated';
          duration_minutes?: number;
          actions_performed: number;
          is_mobile: boolean;
          browser_info: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          session_token: string;
          ip_address?: string;
          user_agent?: string;
          device_info?: any;
          location_info?: any;
          login_time?: string;
          last_activity?: string;
          logout_time?: string;
          status?: 'active' | 'expired' | 'terminated';
          duration_minutes?: number;
          actions_performed?: number;
          is_mobile?: boolean;
          browser_info?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          session_token?: string;
          ip_address?: string;
          user_agent?: string;
          device_info?: any;
          location_info?: any;
          login_time?: string;
          last_activity?: string;
          logout_time?: string;
          status?: 'active' | 'expired' | 'terminated';
          duration_minutes?: number;
          actions_performed?: number;
          is_mobile?: boolean;
          browser_info?: any;
          created_at?: string;
        };
      };
      system_settings: {
        Row: {
          id: string;
          category: string;
          key: string;
          value: string;
          data_type: 'string' | 'number' | 'boolean' | 'json' | 'array';
          description?: string;
          is_public: boolean;
          is_editable: boolean;
          validation_rules: any;
          default_value?: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category: string;
          key: string;
          value: string;
          data_type?: 'string' | 'number' | 'boolean' | 'json' | 'array';
          description?: string;
          is_public?: boolean;
          is_editable?: boolean;
          validation_rules?: any;
          default_value?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category?: string;
          key?: string;
          value?: string;
          data_type?: 'string' | 'number' | 'boolean' | 'json' | 'array';
          description?: string;
          is_public?: boolean;
          is_editable?: boolean;
          validation_rules?: any;
          default_value?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      beneficiaries_detailed: {
        Row: {
          id: string;
          name: string;
          organization_name?: string;
          family_name?: string;
          total_packages_received: number;
          packages_delivered: number;
          last_package_date?: string;
          average_rating?: number;
        };
      };
      system_statistics: {
        Row: {
          total_beneficiaries: number;
          verified_beneficiaries: number;
          active_beneficiaries: number;
          total_packages: number;
          delivered_packages: number;
          active_tasks: number;
          critical_alerts: number;
          active_organizations: number;
          active_couriers: number;
        };
      };
      courier_performance: {
        Row: {
          id: string;
          name: string;
          total_tasks: number;
          successful_deliveries: number;
          failed_deliveries: number;
          behavior_rating?: number;
          time_rating?: number;
          success_rate_calculated: number;
        };
      };
    };
    Functions: {
      calculate_distance: {
        Args: {
          lat1: number;
          lon1: number;
          lat2: number;
          lon2: number;
        };
        Returns: number;
      };
      calculate_courier_success_rate: {
        Args: {
          courier_uuid: string;
        };
        Returns: number;
      };
      generate_tracking_number: {
        Args: {};
        Returns: string;
      };
      search_beneficiaries: {
        Args: {
          search_term: string;
        };
        Returns: {
          id: string;
          name: string;
          national_id: string;
          phone: string;
          address: string;
          status: string;
          identity_status: string;
          rank: number;
        }[];
      };
      get_geographic_statistics: {
        Args: {};
        Returns: {
          area_name: string;
          total_beneficiaries: number;
          delivered_packages: number;
          pending_packages: number;
          success_rate: number;
        }[];
      };
      generate_comprehensive_report: {
        Args: {
          start_date?: string;
          end_date?: string;
        };
        Returns: any;
      };
      create_automatic_alerts: {
        Args: {};
        Returns: void;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// أنواع مساعدة للواجهات
export type Institution = Database['public']['Tables']['institutions']['Row'];
export type InstitutionInsert = Database['public']['Tables']['institutions']['Insert'];
export type InstitutionUpdate = Database['public']['Tables']['institutions']['Update'];

export type PackageItem = Database['public']['Tables']['package_items']['Row'];
export type PackageItemInsert = Database['public']['Tables']['package_items']['Insert'];
export type PackageItemUpdate = Database['public']['Tables']['package_items']['Update'];

export type DeliveryRoute = Database['public']['Tables']['delivery_routes']['Row'];
export type DeliveryRouteInsert = Database['public']['Tables']['delivery_routes']['Insert'];
export type DeliveryRouteUpdate = Database['public']['Tables']['delivery_routes']['Update'];

export type CourierLocation = Database['public']['Tables']['courier_locations']['Row'];
export type CourierLocationInsert = Database['public']['Tables']['courier_locations']['Insert'];
export type CourierLocationUpdate = Database['public']['Tables']['courier_locations']['Update'];

export type BeneficiaryCategory = Database['public']['Tables']['beneficiary_categories']['Row'];
export type BeneficiaryCategoryInsert = Database['public']['Tables']['beneficiary_categories']['Insert'];
export type BeneficiaryCategoryUpdate = Database['public']['Tables']['beneficiary_categories']['Update'];

export type DistributionCenter = Database['public']['Tables']['distribution_centers']['Row'];
export type DistributionCenterInsert = Database['public']['Tables']['distribution_centers']['Insert'];
export type DistributionCenterUpdate = Database['public']['Tables']['distribution_centers']['Update'];

export type InventoryItem = Database['public']['Tables']['inventory']['Row'];
export type InventoryItemInsert = Database['public']['Tables']['inventory']['Insert'];
export type InventoryItemUpdate = Database['public']['Tables']['inventory']['Update'];

export type Notification = Database['public']['Tables']['notifications']['Row'];
export type NotificationInsert = Database['public']['Tables']['notifications']['Insert'];
export type NotificationUpdate = Database['public']['Tables']['notifications']['Update'];

export type UserSession = Database['public']['Tables']['user_sessions']['Row'];
export type UserSessionInsert = Database['public']['Tables']['user_sessions']['Insert'];
export type UserSessionUpdate = Database['public']['Tables']['user_sessions']['Update'];

export type SystemSetting = Database['public']['Tables']['system_settings']['Row'];
export type SystemSettingInsert = Database['public']['Tables']['system_settings']['Insert'];
export type SystemSettingUpdate = Database['public']['Tables']['system_settings']['Update'];

export type GeographicArea = Database['public']['Tables']['geographic_areas']['Row'];
export type GeographicAreaInsert = Database['public']['Tables']['geographic_areas']['Insert'];
export type GeographicAreaUpdate = Database['public']['Tables']['geographic_areas']['Update'];

export type EmergencyContact = Database['public']['Tables']['emergency_contacts']['Row'];
export type EmergencyContactInsert = Database['public']['Tables']['emergency_contacts']['Insert'];
export type EmergencyContactUpdate = Database['public']['Tables']['emergency_contacts']['Update'];

export type FeedbackRecord = Database['public']['Tables']['feedback']['Row'];
export type FeedbackInsert = Database['public']['Tables']['feedback']['Insert'];
export type FeedbackUpdate = Database['public']['Tables']['feedback']['Update'];

// أنواع للـ Views
export type BeneficiaryDetailed = Database['public']['Views']['beneficiaries_detailed']['Row'];
export type SystemStatistics = Database['public']['Views']['system_statistics']['Row'];
export type CourierPerformance = Database['public']['Views']['courier_performance']['Row'];

// أنواع للدوال
export type SearchBeneficiariesResult = Database['public']['Functions']['search_beneficiaries']['Returns'][0];
export type GeographicStatisticsResult = Database['public']['Functions']['get_geographic_statistics']['Returns'][0];